x-common-variables: &common
  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dobby-db:5432/${POSTGRES_DB}?sslmode=disable

services:
  dobby-db:
    image: postgres:17-alpine
    container_name: dobby-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - homelab

  dbmate:
    image: amacneil/dbmate
    container_name: dobby-dbmate
    volumes:
      - ./apps/db:/db
    environment:
      <<: *common
    networks:
      - homelab
    command: ["up"]
    depends_on:
      - dobby-db

  backend:
    build:
      context: ./apps/backend
      args:
       - GOMEMLIMIT
    container_name: dobby-backend
    restart: unless-stopped
    environment:
      OIDC_AUTHORITY:
      OIDC_BACKEND_CLIENT_ID:
      OIDC_BACKEND_CLIENT_SECRET:
      BACKEND_PORT:
      ALLOWED_ORIGINS:
      <<: *common
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab"
      - "traefik.http.routers.dobby-api.rule=Host(`api.dobby.homelab.chapar.tech`)"
      - "traefik.http.routers.dobby-api.entrypoints=websecure"
      - "traefik.http.routers.dobby-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.dobby-api.loadbalancer.server.port=${BACKEND_PORT}"
      - "traefik.http.middlewares.dobby-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE"
      - "traefik.http.middlewares.dobby-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.dobby-cors.headers.accesscontrolalloworiginlist=${ALLOWED_ORIGINS}"
      - "traefik.http.middlewares.dobby-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.dobby-cors.headers.addvaryheader=true"
      - "traefik.http.routers.dobby-api.middlewares=dobby-cors"
    depends_on:
      - dobby-db
      - dbmate

  frontend:
    build:
      context: ./apps/frontend/
      args:
        - VITE_API_BASE_URL=https://${BACKEND_HOST}
        - VITE_OIDC_AUTHORITY=${OIDC_AUTHORITY}
        - VITE_OIDC_CLIENT_ID=${OIDC_FRONTEND_CLIENT_ID}
    container_name: dobby-frontend
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab"
      - "traefik.http.routers.dobby-frontend.rule=Host(`dobby.homelab.chapar.tech`)"
      - "traefik.http.routers.dobby-frontend.entrypoints=websecure"
      - "traefik.http.routers.dobby-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.dobby-frontend.loadbalancer.server.port=80"
    depends_on:
      - backend

networks:
  homelab:
    external: true

volumes:
  db-data:
